### ISSUE TITLE
Build instructions?

### ISSUE THREAD

**Issue by abarnert** [request-laurent/sos.battle#1]
As far as I can tell, there are no build instructions anywhere. But there is an Eclipse .project file, so I installed Eclipse and opened it, and it fails because there are multiple missing unspecified dependencies. The first one is SAPUI5, so I went looking for SAPUI5 for Eclipse, and discovered that it's been unsupported since 2019.

So, do I need to get an old version of Eclipse and manually install an old version of SAPUI5 into it? Or learn enough about Eclipse-maven projects to convert it into a standalone maven project? Or…?

Or is there a way of building this as-is?

**Comment by request-laurent** [comment]
Hi @abarnert ,
I updated README to add Build instructions :
https://github.com/request-laurent/sos.battle/blob/master/README.md

I tested in standanlone and it works
